In [1]:
import numpy as np

### Arrays

In [2]:
A=np.zeros((3,4,3))
A

array([[[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]]])

In [7]:
B=np.ones((4,5))
B

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [12]:
C=np.eye(3,5)
C

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.]])

In [17]:
A=np.array([[1,2,3],[4,5,6],[7,8,9]])
A

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [18]:
A.shape

(3, 3)

In [19]:
A.size

9

In [20]:
A.diagonal()

array([1, 5, 9])

In [21]:
np.linalg.inv(A)

LinAlgError: Singular matrix

In [22]:
np.linalg.det(A)

0.0

In [30]:
A=np.array([[1,2,3],[4,-2,-3],[7,8,-9]])
A

array([[ 1,  2,  3],
       [ 4, -2, -3],
       [ 7,  8, -9]])

In [31]:
np.linalg.det(A)

209.99999999999994

In [32]:
np.linalg.inv(A)

array([[ 0.2       ,  0.2       ,  0.        ],
       [ 0.07142857, -0.14285714,  0.07142857],
       [ 0.21904762,  0.02857143, -0.04761905]])

In [33]:
np.linalg.eigvals(A)

array([ 3.82566671+0.j        , -6.91283335+2.66554457j,
       -6.91283335-2.66554457j])

In [34]:
np.linalg.eig(A)

(array([ 3.82566671+0.j        , -6.91283335+2.66554457j,
        -6.91283335-2.66554457j]),
 array([[ 0.78140269+0.j        ,  0.30806784+0.20860998j,
          0.30806784-0.20860998j],
        [ 0.23986073+0.j        , -0.45139939-0.41476374j,
         -0.45139939+0.41476374j],
        [ 0.57608737+0.j        , -0.69698329+0.j        ,
         -0.69698329-0.j        ]]))

In [36]:
A.dot(np.linalg.inv(A))

array([[ 1.00000000e+00, -1.04083409e-17,  0.00000000e+00],
       [ 1.11022302e-16,  1.00000000e+00,  0.00000000e+00],
       [ 1.11022302e-16, -7.97972799e-17,  1.00000000e+00]])

In [37]:
A=A.reshape((1,9))
A

array([[ 1,  2,  3,  4, -2, -3,  7,  8, -9]])

In [38]:
A.argmax()

7

In [39]:
A.max()

8

In [41]:
A.argmin()

8

In [42]:
A.min()

-9

In [30]:
np.invert(A)

array([[ -2,  -3,  -4],
       [ -5,  -6,  -7],
       [ -8,  -9, -10]])

In [29]:
A

array([[ 1,  2,  3,  4, -2, -3,  7,  8,  9]])

In [45]:
np.random.normal(0.1,0.4,size=(3,4))

array([[ 0.5487385 ,  0.41833371, -0.09342698,  0.72079143],
       [-0.16139249,  0.20547016,  0.42220358,  0.48259852],
       [ 0.58542227, -0.07199945, -0.15905867, -0.59815118]])

In [50]:
E=np.random.random((3,4))
E

array([[0.91905356, 0.71788744, 0.92266611, 0.83584861],
       [0.23247302, 0.41558955, 0.11425188, 0.74649641],
       [0.70540996, 0.69411069, 0.48085735, 0.93515167]])

In [47]:
F=np.random.randint(10,size=(3,7))
F

array([[3, 1, 8, 0, 6, 3, 4],
       [7, 7, 0, 3, 4, 7, 6],
       [4, 2, 9, 2, 5, 1, 6]])

In [48]:
G=np.sqrt(F)
G

array([[1.73205081, 1.        , 2.82842712, 0.        , 2.44948974,
        1.73205081, 2.        ],
       [2.64575131, 2.64575131, 0.        , 1.73205081, 2.        ,
        2.64575131, 2.44948974],
       [2.        , 1.41421356, 3.        , 1.41421356, 2.23606798,
        1.        , 2.44948974]])

In [49]:
F=np.array([[1,2,3],[4,5,6],[7,8,9]])
G=np.log(F)
G

array([[0.        , 0.69314718, 1.09861229],
       [1.38629436, 1.60943791, 1.79175947],
       [1.94591015, 2.07944154, 2.19722458]])

In [50]:
np.exp(F)

array([[2.71828183e+00, 7.38905610e+00, 2.00855369e+01],
       [5.45981500e+01, 1.48413159e+02, 4.03428793e+02],
       [1.09663316e+03, 2.98095799e+03, 8.10308393e+03]])

In [57]:
H=np.array([i for i in range(12,50,5)])
H

array([12, 17, 22, 27, 32, 37, 42, 47])

In [60]:
H= np.array([i if (i%2==0 and i%3==2) else  10-i     for i  in range(12,50,5)])
H

array([ -2,  -7, -12, -17,  32, -27, -32, -37])

In [61]:
def function(i):
    if (i%2==0 and i%3==2):
        return i
    else:
        return 10-i

In [62]:
H=np.array([ function(i)  for i  in range(12,50,5) ])
H

array([ -2,  -7, -12, -17,  32, -27, -32, -37])

In [63]:
H.size

8

In [64]:
H=H.reshape((2,4))

In [65]:
H

array([[ -2,  -7, -12, -17],
       [ 32, -27, -32, -37]])

In [66]:
np.sum(H,axis=1)

array([-38, -64])

In [67]:
np.sum(H,axis=0)

array([ 30, -34, -44, -54])

In [69]:
H.sum(axis=1)

array([-38, -64])

In [65]:
np.sum(H)

-102

In [66]:
A=np.random.random((5,8))
B=np.random.random((5,8))

In [68]:
A

array([[0.23109696, 0.8698287 , 0.1997581 , 0.50876064, 0.77985749,
        0.35638839, 0.49937397, 0.15792676],
       [0.30536877, 0.85081992, 0.09058034, 0.05885319, 0.18822408,
        0.63647011, 0.86708932, 0.04679552],
       [0.54424269, 0.68878531, 0.78204552, 0.49662192, 0.87390909,
        0.39019034, 0.53692998, 0.74715808],
       [0.12546559, 0.26472541, 0.85394871, 0.06232374, 0.76824151,
        0.73759152, 0.70139303, 0.62434132],
       [0.40433115, 0.91790167, 0.96382331, 0.29227468, 0.2996082 ,
        0.4172732 , 0.25384812, 0.56654098]])

In [69]:
B

array([[0.71535917, 0.86993521, 0.22794822, 0.46875509, 0.50518286,
        0.76975254, 0.31962828, 0.08721396],
       [0.95571271, 0.48710702, 0.49286572, 0.30334442, 0.36472737,
        0.34414579, 0.26756619, 0.20438251],
       [0.6518553 , 0.99276638, 0.06793063, 0.69080096, 0.98716174,
        0.06200063, 0.0799896 , 0.2878206 ],
       [0.24250227, 0.70271115, 0.74307871, 0.36243225, 0.27724414,
        0.03966268, 0.73989201, 0.52408864],
       [0.61495969, 0.18437019, 0.97019028, 0.33067862, 0.70149234,
        0.55179914, 0.52876033, 0.98401091]])

In [67]:
A+B

array([[0.94645613, 1.73976391, 0.42770632, 0.97751573, 1.28504035,
        1.12614092, 0.81900225, 0.24514072],
       [1.26108148, 1.33792694, 0.58344605, 0.36219761, 0.55295145,
        0.9806159 , 1.13465551, 0.25117802],
       [1.19609798, 1.68155169, 0.84997615, 1.18742288, 1.86107082,
        0.45219098, 0.61691958, 1.03497869],
       [0.36796786, 0.96743657, 1.59702742, 0.42475599, 1.04548565,
        0.77725421, 1.44128503, 1.14842996],
       [1.01929084, 1.10227187, 1.93401359, 0.6229533 , 1.00110055,
        0.96907234, 0.78260845, 1.55055189]])

In [70]:
A-B

array([[-4.84262212e-01, -1.06513792e-04, -2.81901234e-02,
         4.00055513e-02,  2.74674630e-01, -4.13364149e-01,
         1.79745696e-01,  7.07128049e-02],
       [-6.50343947e-01,  3.63712900e-01, -4.02285378e-01,
        -2.44491226e-01, -1.76503297e-01,  2.92324314e-01,
         5.99523131e-01, -1.57586988e-01],
       [-1.07612609e-01, -3.03981073e-01,  7.14114881e-01,
        -1.94179041e-01, -1.13252649e-01,  3.28189711e-01,
         4.56940385e-01,  4.59337482e-01],
       [-1.17036685e-01, -4.37985742e-01,  1.10869992e-01,
        -3.00108504e-01,  4.90997375e-01,  6.97928838e-01,
        -3.84989795e-02,  1.00252682e-01],
       [-2.10628545e-01,  7.33531480e-01, -6.36697408e-03,
        -3.84039376e-02, -4.01884136e-01, -1.34525945e-01,
        -2.74912212e-01, -4.17469927e-01]])

In [71]:
A.T

array([[0.23109696, 0.30536877, 0.54424269, 0.12546559, 0.40433115],
       [0.8698287 , 0.85081992, 0.68878531, 0.26472541, 0.91790167],
       [0.1997581 , 0.09058034, 0.78204552, 0.85394871, 0.96382331],
       [0.50876064, 0.05885319, 0.49662192, 0.06232374, 0.29227468],
       [0.77985749, 0.18822408, 0.87390909, 0.76824151, 0.2996082 ],
       [0.35638839, 0.63647011, 0.39019034, 0.73759152, 0.4172732 ],
       [0.49937397, 0.86708932, 0.53692998, 0.70139303, 0.25384812],
       [0.15792676, 0.04679552, 0.74715808, 0.62434132, 0.56654098]])

In [72]:
A.T.dot(B)

array([[1.09100267, 1.05280518, 0.72566365, 0.7560996 , 1.08379793,
        0.54480812, 0.50573049, 0.70283252],
       [2.51303675, 2.21019708, 1.7516566 , 1.54111714, 2.14697693,
        1.52206114, 1.24198636, 1.48996535],
       [1.53904507, 1.77206699, 1.71294641, 1.28956677, 1.81882384,
        0.79913124, 1.29210143, 1.65698101],
       [0.93876976, 1.06196847, 0.50858715, 0.71864095, 0.99103602,
        0.60641359, 0.41874209, 0.51960225],
       [1.6779759 , 2.23278902, 1.19144241, 1.40386565, 1.74847403,
        0.91505079, 1.09636722, 1.0554576 ],
       [1.55304974, 1.60267825, 1.37436123, 1.03498267, 1.29456723,
        0.77706728, 1.08179644, 1.07063493],
       [1.86211646, 1.92951306, 1.34513521, 1.20617214, 1.47109273,
        0.88398183, 1.08774655, 0.99269121],
       [1.14454044, 1.44511879, 1.12340525, 1.01798607, 1.4049345 ,
        0.52137316, 0.88427318, 1.12307779]])

In [74]:
A*B

array([[0.16531733, 0.75669461, 0.0455345 , 0.23848414, 0.39397064,
        0.27433086, 0.15961404, 0.01377342],
       [0.29184481, 0.41444036, 0.04464394, 0.01785279, 0.06865047,
        0.21903851, 0.23200379, 0.00956419],
       [0.35476748, 0.6838029 , 0.05312485, 0.3430669 , 0.86268961,
        0.02419205, 0.04294881, 0.21504749],
       [0.03042569, 0.1860255 , 0.63455111, 0.02258813, 0.21299045,
        0.02925486, 0.51895509, 0.3272102 ],
       [0.24864736, 0.16923371, 0.93509201, 0.09664899, 0.21017286,
        0.23025099, 0.13422481, 0.5574825 ]])

In [77]:
D=np.random.random((5,8))
D

array([[0.80642881, 0.7877524 , 0.67034917, 0.13360693, 0.67563976,
        0.98308587, 0.3504024 , 0.55951734],
       [0.11042336, 0.83408701, 0.08359943, 0.2235462 , 0.94367294,
        0.28333592, 0.30225285, 0.12026535],
       [0.36844806, 0.82894551, 0.67236736, 0.52283722, 0.2997568 ,
        0.56381476, 0.9671399 , 0.33614874],
       [0.84493625, 0.85280171, 0.24667259, 0.12798415, 0.31913767,
        0.27798358, 0.14087215, 0.23513889],
       [0.56310733, 0.47374686, 0.7296997 , 0.51787633, 0.26350321,
        0.13010858, 0.04192345, 0.57605385]])

In [78]:
C=np.array(D*100,dtype=int)
C

array([[80, 78, 67, 13, 67, 98, 35, 55],
       [11, 83,  8, 22, 94, 28, 30, 12],
       [36, 82, 67, 52, 29, 56, 96, 33],
       [84, 85, 24, 12, 31, 27, 14, 23],
       [56, 47, 72, 51, 26, 13,  4, 57]])

In [80]:
D=np.linspace(1,120,5)
D

array([  1.  ,  30.75,  60.5 ,  90.25, 120.  ])

In [70]:
F=np.array([i for i in range(120)])
F

array([  0,   1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,
        13,  14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,
        26,  27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,
        39,  40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  51,
        52,  53,  54,  55,  56,  57,  58,  59,  60,  61,  62,  63,  64,
        65,  66,  67,  68,  69,  70,  71,  72,  73,  74,  75,  76,  77,
        78,  79,  80,  81,  82,  83,  84,  85,  86,  87,  88,  89,  90,
        91,  92,  93,  94,  95,  96,  97,  98,  99, 100, 101, 102, 103,
       104, 105, 106, 107, 108, 109, 110, 111, 112, 113, 114, 115, 116,
       117, 118, 119])

In [71]:
F[F%7==1]

array([  1,   8,  15,  22,  29,  36,  43,  50,  57,  64,  71,  78,  85,
        92,  99, 106, 113])

In [77]:
F[((F%3==0) & (F%4==2)) | (F%5==1)]

array([  1,   6,  11,  16,  18,  21,  26,  30,  31,  36,  41,  42,  46,
        51,  54,  56,  61,  66,  71,  76,  78,  81,  86,  90,  91,  96,
       101, 102, 106, 111, 114, 116])

In [90]:
a = np.array([1, 3, 0], float) 
    
np.where(a != 0, 1 / a, a)

<ipython-input-90-a6fd627f9e16>:3: RuntimeWarning: divide by zero encountered in true_divide
  np.where(a != 0, 1 / a, a)


array([1.        , 0.33333333, 0.        ])

In [78]:
g=np.random.random((3,5))*100
g

array([[15.02249345, 14.61300176, 70.92975517, 61.29153822, 21.00758255],
       [19.81575838,  8.97759357,  7.00928194, 78.31827818, 88.59223034],
       [17.60660897, 86.93734412, 25.33312068, 12.871229  , 91.14221306]])

In [79]:
g.max()

91.14221305632168

In [80]:
g.argmax()

14

In [81]:
g.mean()

41.29786862608408

In [82]:
g.argsort(axis=0)

array([[0, 1, 1, 2, 0],
       [2, 0, 2, 0, 1],
       [1, 2, 0, 1, 2]])

In [83]:
g.argsort(axis=1)

array([[1, 0, 4, 3, 2],
       [2, 1, 0, 3, 4],
       [3, 0, 2, 1, 4]])

In [107]:
g.flatten()

array([53.55384602, 16.29492612, 66.31507401,  2.02902145, 69.95145382,
       34.47232512, 75.31980171, 33.55653787, 27.04551333, 89.53952797,
       49.97366496, 44.47985272, 50.556283  , 63.49211644, 35.55842529])

In [85]:
g.repeat(3)

array([15.02249345, 15.02249345, 15.02249345, 14.61300176, 14.61300176,
       14.61300176, 70.92975517, 70.92975517, 70.92975517, 61.29153822,
       61.29153822, 61.29153822, 21.00758255, 21.00758255, 21.00758255,
       19.81575838, 19.81575838, 19.81575838,  8.97759357,  8.97759357,
        8.97759357,  7.00928194,  7.00928194,  7.00928194, 78.31827818,
       78.31827818, 78.31827818, 88.59223034, 88.59223034, 88.59223034,
       17.60660897, 17.60660897, 17.60660897, 86.93734412, 86.93734412,
       86.93734412, 25.33312068, 25.33312068, 25.33312068, 12.871229  ,
       12.871229  , 12.871229  , 91.14221306, 91.14221306, 91.14221306])

In [ ]:
np.

### refrence

https://cs231n.github.io/python-numpy-tutorial/

http://index-of.es/Varios-2/NumPy%20Tutorial.pdf

https://sites.engineering.ucsb.edu/~shell/che210d/numpy.pdf

https://numpy.org/doc/1.20/numpy-user.pdf